# Generated by Django 5.2.7 on 2025-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, default='default/aluno.png', null=True, upload_to='alunos/')),
                ('cursos', models.ManyToManyField(blank=True, related_name='alunos', to='cursos.curso')),
            ],
        ),
    ]
