# Generated by Django 5.2.7 on 2025-10-24 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.ImageField(blank=True, default='default/curso.png', null=True, upload_to='cursos/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='professor.professor')),
            ],
        ),
    ]
